### ISSUE TITLE
Enhancement: Add script builder to tools list

### ISSUE THREAD

**Issue by sabberworm** [swisscom/JCR-Hopper#18]
It would be cool if the script builder showed up here:

![image](https://github.com/user-attachments/assets/3301a7e5-bce8-41f6-a280-6c3f623b2c98)

ACS-Commons, if installed, also get an entry. However, I have not, on first try, been able to figure out how they do it.

**Comment by SgiobairOg** [comment]
Is this what we're after? https://hashouttech.com/blog/creating-a-tool-in-adobe-experience-manager
